### ISSUE TITLE
Write another example of a foundational pattern (similar to tree)

### ISSUE THREAD

**Issue by cparedis** [st4se/playground#29]

**Comment by cparedis** [comment]
Maybe "transitive closure" or "cut-set" could be an interesting concept to describe

**Comment by HensonGraves** [comment]
Patterns in ontologies
Patterns as they occur in ontologies are in general not definable within the ontology. Rather they are descriptions of classes of ontologies.  A pattern is described within the metalanguage or metalogic of the ontology.  Here are three examples
1. Amino acids form a pattern as they specify some specific atoms and connections but may have “side chains”. The R in the diagram is a placeholder for a side chain.  Not just any molecule will work as a side chain for an amino acid. Look at the diagram in Wikipedia.
 
2. A distributed network consisting of an arbitrary collection of ordinary nodes together with nodes, which I will call routers. Each node is reachable through at least one collection of router. 
3. One can define a Mission context as a pattern. The mission context has a terrain, weather, laws of physics, and one or more systems of interest. A system such as a satellite and ground system may be distributed.

**Comment by HensonGraves** [comment]
"write another example of a foundation pattern (similar to tree) " sounds like homework problem for a SR$SE class.

**Comment by HensonGraves** [comment]
As some of you likely know there is a whole cottage industry devoted to ontology patterns. Participants include Gangemi, https://link.springer.com/chapter/10.1007/11574620_21 and Hitzler,  http://ceur-ws.org/Vol-2043/paper-09.pdf. The patterns tend to be very domain oriented.  Gangemi suggests a documentation framework based on meta data.  These patterns are not likely to have any meaningful axioms in the foreseeable future as they depend so much on domain knowledge.  Hitzler states in one of his papers that he is unaware of any real use of reasoning.
The reason that I suggested Tree as a pattern is that not only does it occur frequently, but axioms can be given that can be checked and can be used to determine problematics relationships between  multiple trees such as requirements decompositions and product decompositions.
